steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Install functions dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'installfunctions']
# Build server and webpack
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build2']
# Build app and prerender
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build4']
# Deploy to firebase hosting
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'hosting']