steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build2']
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']